apiVersion: apps/v1
kind: Deployment
metadata:
  name: microsoft-python-discord-bot
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: microsoft-python-discord-bot
  template:
    metadata:
      labels:
        app: microsoft-python-discord-bot
    spec:
      containers:
        - name: bot
          image: docker.pkg.github.com/jb3/microsoft-python-discord-bot/bot
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: microsoft-bot-token
