name: Deploy to Azure

on:
  registry_package:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Login to Azure CLI
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: Deploy to Azure
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
            image: docker.pkg.github.com/j03b/microsoft-python-discord-bot/bot:latest
            registry-login-server: docker.pkg.github.com
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
            secure-environment-variables: TOKEN=${{ secrets.DISCORD_TOKEN }}
            name: bot
            location: 'central us'
