name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_docker_image:
    name: Test building Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test build Docker image
        run: docker build . --file Dockerfile

  push_docker_image:
    name: Build & Publish Docker image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile -t j03b/microsoft-python-discord-bot/bot:latest

      - name: Publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: j03b/microsoft-python-discord-bot/bot
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

  deploy_to_azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [push_docker_image]

    steps:
    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: mp-db # Microsoft Python Discord Bot
        image: docker.pkg.github.com/j03b/microsoft-python-discord-bot/bot:latest
        registry-login-server: docker.pkg.github.com
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        secure-environment-variables: TOKEN=${{ secrets.DISCORD_TOKEN }}
        name: bot
        location: 'central us'
